ALTER TABLE `Sale`
  ADD COLUMN `gstMode` VARCHAR(191) NOT NULL DEFAULT 'B2C',
  ADD COLUMN `hsn` VARCHAR(191) NOT NULL DEFAULT '';

ALTER TABLE `SaleItem`
  ADD COLUMN `hsn` VARCHAR(191) NOT NULL DEFAULT '';
