ALTER TABLE `Product` ADD COLUMN `hsn` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `StockInItem` ADD COLUMN `hsn` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `PurchaseItem` ADD COLUMN `hsn` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Purchase` ADD COLUMN `received` BOOLEAN NOT NULL DEFAULT false;
