ALTER TABLE `PurchaseItem`
  ADD COLUMN `packs` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `volume` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `inBillDiscountPercent` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `inBillDiscountAmount` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `inBillDiscount2Percent` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `inBillDiscount2Amount` DOUBLE NOT NULL DEFAULT 0;
